image: sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.2_13_1.10.4_2.13.15

stages:
  - compile
  - test
  - docker

variables:
  SBT_OPTS: "-Xmx1G"

before_script:
  - sbt clean update

compile:
  stage: compile
  script:
    - sbt "scalafmtCheckAll; compile"

test:
  stage: test
  script:
    - sbt test