volumes:
  sclaus-postgres-data:
    driver: local

  sclaus-kafka-data:
    driver: local

services:
  postgres:
    image: postgres:15.4
    hostname: sclaus-postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:32004:5432"
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE:-sclaus}
    volumes:
      - sclaus-postgres-data:/var/lib/postgresql/data:rw
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${PG_USERNAME} -d ${PG_DATABASE:-sclaus}'",
        ]
      interval: 30s
      timeout: 60s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:7.7
    hostname: sclaus-pgadmin
    restart: unless-stopped
    ports:
      - "127.0.0.1:32005:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      platforms:
        - linux/amd64
    hostname: sclaus-server
    restart: unless-stopped
    ports:
      - "127.0.0.1:32006:8080"
    volumes:
      - ./src/main/resources/application.conf:/app/resources/application.conf:ro
      - ./src/main/resources/logback.xml:/app/resources/logback.xml:ro
    depends_on:
      postgres:
        condition: service_healthy
